openapi: 3.0.1
info:
  title: monster-otyugh
  x-cortex-tag: monster-otyugh
  x-cortex-custom-metadata:
    alignment: lawful-good
    type: elemental
    challenge_rating: 20
    legendary: false
    armor_class: 18
    hit_points: 268
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-otyugh
      alias: github-token-test
